app_path: /app
component: shipping
schema_setup: mysql
schema_files:
  - schema
  - master-data
  - app-user

secrets: "{{ lookup('harshi_vault', 'secret=project-{{env}}/data/shipping token={{vault_token}} url=https://vault.adevops.click:8200 validate_certs=false')}}"  